### ISSUE TITLE
Required dependency failed

### ISSUE THREAD

**Issue by schmasterz** [yiisoft/yii-debug#11]
### What steps will reproduce the problem?
composer update
### What's expected?

Successful packages update

### What do you get instead?
   - Installation request for yiisoft/yii-debug dev-master -> satisfiable by yiisoft/yii-debug[dev-master].
    - yiisoft/yii-debug dev-master requires yiisoft/yii-bootstrap-implementation ^3.0@dev -> no matching package found.

### Additional info

yii-base-web composer.json :
```javascript
 "require-dev": {
        "yiisoft/yii-debug": "dev-master",
        "yiisoft/yii-gii": "dev-master",
        "phpunit/phpunit": "^7.0"
    }, 
```
What is the idea of yiisoft/yii-bootstrap-implementation?
| Q                | A
| ---------------- | ---
| Yii version      | 3.0
| PHP version      | PHP 7.2.10-0ubuntu0.18.04.1 
| Operating system | Ubuntu 18.0.4.1

**Comment by samdark** [comment]
We'll get rid of this dependency soon. @simialbi already did for Yii 2.

**Comment by machour** [comment]
I'd be happy to port https://github.com/yiisoft/yii2-debug/commit/097f7e52eaa3e46c33d20802fcc72904b35e2688 to this repository, if it's okay with @simialbi (👋 )

I'm just confused by one thing: Why is there still work being done in yii2-debug 2.1? (as I understand it, there will be no Yii 2.1 release, and we should focus all efforts on 3.0)

**Comment by samdark** [comment]
@simialbi yes, it is definitely acceptable and is very much needed for the whole idea of Yii 3.0 to work well.

**Comment by samdark** [comment]
@machour 2.1 doesn't mean it's for Yii 2.1. It's just SemVer.

**Comment by schmasterz** [comment]
Related: https://github.com/yiisoft/yii-debug/pull/14

**Comment by samdark** [comment]
@pistej is this one fixed now?

**Comment by pistej** [comment]
@samdark yes, can be closed.
