### ISSUE TITLE
Remove yiisoft/cache dependecy

### ISSUE THREAD

**Issue by vjik** [yiisoft/yii-debug#134]
Seems, Yii Cache don't use in this package.

**Comment by rustamwin** [comment]
https://github.com/yiisoft/yii-debug/blob/master/config/params.php#L58

**Comment by vjik** [comment]
> https://github.com/yiisoft/yii-debug/blob/master/config/params.php#L58

This is config. The package itself does not require Yii Cache.

See [docs](https://github.com/yiisoft/docs/blob/master/000-packages.md#configs-and-defaults):
> Package must not have dependencies in require section of composer.json that are used in config only.
