### ISSUE TITLE
Provide support for log collection from Monolog

### ISSUE THREAD

**Issue by klimov-paul** [yiisoft/yii-debug#16]
Since Yii 2.1 adopted PSR Log, usage of the [Monolog](https://github.com/Seldaek/monolog) instead of standard Yii logger is very likely.
Thus it should be support for extracting information for debug toolbar from Monolog.
This could be achived creating our own log handler for the Monolog logger and attaching it in the same way as current `LogTarget`.

See:
https://github.com/Seldaek/monolog/blob/master/src/Monolog/Handler/AbstractProcessingHandler.php

**Comment by rustamwin** [comment]
Since we've adopted PSR log, any PSR logger implementation will be collected.
