### ISSUE TITLE
Profile cache level

### ISSUE THREAD

**Issue by vitalyzhakov** [yiisoft/yii-debug#20]
### What steps will reproduce the problem?

Process connect to several cache systems. For performance purposes programmers need to know how effectively use cache.
### What is the expected result?

In debug panel: performance, time to do query.
### What do you get instead?

Nothing in debug panel if I use memcache.
### Additional info

| Q | A |
| --- | --- |
| Yii version | 2.0.9 |
| PHP version | 7.0.12 |
| Operating system | Debian 8, Docker |

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2/pull/12911

**Comment by rustamwin** [comment]
Move to the cache package?

**Comment by samdark** [comment]
@rustamwin can't we measure time based on data collected via container proxy calls? https://github.com/yiisoft/yii-debug/blob/master/src/Proxy/ProxyLogTrait.php

**Comment by rustamwin** [comment]
Yes, of course.
