### ISSUE TITLE
Log page output.

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-debug#23]
I think the ability to store output data would be killer-feature for yii-debug.

Things which we can log:
- Page output
- CSS filles
- JS files
- Images
- Fonts
- Screenshot of page

It very useful for ajax or api requests.

**Comment by samdark** [comment]
By "store" do you mean export?

**Comment by samdark** [comment]
@xepozz is that for recording/comparing or for analyzing current page? If latter, Chrome, Firefox or IE dev tools have this information.

**Comment by xepozz** [comment]
It is for all pages on site, not for current only.
Web browsers can log reqest output from self, but how will be log output from callback-requests (callback api), from mobile apps (api) or others (bots, direct requests)?

Also after refresh dev-tool page all information about requests will be trashed.

**Comment by rustamwin** [comment]
Except `Screenshot of the page` item, we can do it.
