### ISSUE TITLE
Separate debugging and showing results

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-debug#26]
For real projects it would be nice to have debugging in producation.
Thus it should be two independent processes: writing and reading.

Now we're ready to enable debug for few time on production server to collect information (ex. when server have peak load or just regulary statistics)

**Comment by samdark** [comment]
In Yii 2 it was not recommended to enable debug in production because:

1. Security.
2. Performance.

This feature would solve security issue so it will be safe to enable it at least.

**Comment by kamarton** [comment]
The #28  ticket could be used to match tags to a given page, so the rendering would not be associated with that developer's session, but could be viewed globally. eg. tags `app:<app id>`, `session:<sessionid>`, `user:<user id>`, `route:<module>/<controller>/<action>`.

For example, if the panel show on the backend, it would filter to `app:backend` and `session: 2384923893r89wewf` by default. 

I suggest that also have the option to add own labels.
