### ISSUE TITLE
Multi server support for debug panel

### ISSUE THREAD

**Issue by kamarton** [yiisoft/yii-debug#28]
### What steps will reproduce the problem?

Yii2 store debug data into files, this solution is not suitable for multi-server environments. The problem is similar to https://github.com/yiisoft/view/issues/51.

### What is the expected result?

Support cloud platforms with LB.

### What do you get instead?

Yii2 does not support it due to file storage.

### Suggests

Storage interface should be defined, which already allows to using eg. redis, mysql.

| Q                | A
| ---------------- | ---
| Version          | 3.0.x-dev
| PHP version      | -
| Operating system | -

**Comment by samdark** [comment]
Agree.

**Comment by SamMousa** [comment]
Given the type of data is likely to be ephemeral, how about using a cache for this?

If the data is not available it 's usually not a big issue; assuming you don't store debug data for long periods of time anyway.

Cache has widely supported implementations anyway.

**Comment by samdark** [comment]
While cache could be used, I think an interface for debug data should be added so more sophisticated implementations could be added later.

**Comment by SamMousa** [comment]
Makes sense, initial implementation could then be an adapter for a cache:
```php

class CacheStorage implements DebugStorage {
    public function __construct(CacheInterface $cache) {
    ...
    }

    public function store(...) {
        $this->cache->set($key, $value);
    }
}
```
