### ISSUE TITLE
Debug always logs the same amount of memory used

### ISSUE THREAD

**Issue by evil1** [yiisoft/yii-debug#71]
### What steps will reproduce the problem?
Clean install of `yiisoft/yii-demo` or `yiisoft/app-api` and enable debug in params

### What is the expected result?
Actual memory usage to be recorded

### What do you get instead?
Always the same memory amount is recorded

### Additional info

| Q                | A
| ---------------- | ---
| Version          | 3.0@dev
| PHP version      | 7.4.5
| Operating system | Win 10 and Ubuntu 20.04

**Comment by samdark** [comment]
@rustamwin would you please take a look?

**Comment by rustamwin** [comment]
> @rustamwin would you please take a look?

Yes.
