### ISSUE TITLE
Config Exception, missed class element

### ISSUE THREAD

**Issue by gbi46** [yiisoft/yii-debug#8]
When its set in config '__class' => yii\debug\Module::class, - then

Exception (Invalid Configuration) 'yii\base\InvalidConfigException' with message 'Object configuration must be an array containing a "class" element.'

**Comment by samdark** [comment]
Do you use it with Yii 3.0?

**Comment by samdark** [comment]
Then why using `__class` instead of `class`?

**Comment by hiqsol** [comment]
You need to use `yiisoft/yii2-debug` package in Yii 2.

**Comment by gbi46** [comment]
Thank you! There was confusion!
